### Lab: Data Analysis with Pandas
##### bike-stats | Nizar Alsaeed | 24-05-2021

In [1]:
import pandas as pd

## Part1: bike data

#### Cleaning the data

In [2]:
#cleaning the data first; it seems that two tables were joined together and the header of the 
#second table appears as a data row
df = pd.read_csv('./archive/trip.csv',low_memory=False)
df.loc[df['trip_id'] == 'trip_id']

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_name,to_station_name,from_station_id,to_station_id,usertype,gender,birthyear
50793,trip_id,starttime,stoptime,bikeid,tripduration,from_station_name,to_station_name,from_station_id,to_station_id,usertype,gender,birthyear

In [3]:
#dropping that row
df = df.drop(50793,axis=0)
df.loc[df['trip_id'] == 'trip_id']

Empty DataFrame
Columns: [trip_id, starttime, stoptime, bikeid, tripduration, from_station_name, to_station_name, from_station_id, to_station_id, usertype, gender, birthyear]
Index: []

In [4]:
df

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_name,to_station_name,from_station_id,to_station_id,usertype,gender,birthyear
0,431,10/13/2014 10:31,10/13/2014 10:48,SEA00298,985.935,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1960
1,432,10/13/2014 10:32,10/13/2014 10:48,SEA00195,926.375,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1970
2,433,10/13/2014 10:33,10/13/2014 10:48,SEA00486,883.831,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,1988
3,434,10/13/2014 10:34,10/13/2014 10:48,SEA00333,865.937,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,1977
4,435,10/13/2014 10:34,10/13/2014 10:49,SEA00202,923.923,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1971
5,436,10/13/2014 10:34,10/13/2014 10:47,SEA00337,808.805,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1974
6,437,10/13/2014 11:35,10/13/2014 11:45,SEA00202,596.715,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1978
7,438,10/13/2014 11:35,10/13/2014 11:45,SEA00311,592.131,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1983
8,439,10/13/2014 11:35,10/13/2014 11:45,SEA00486,586.347,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Female,1974
9,440,10/13/2014 11:35,10/13/2014 11:45,SEA00434,587.634,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1958
10,441,10/13/2014 11:36,10/13/2014 11:45,SEA00195,564.899,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Female,1983
11,442,10/13/2014 11:37,10/13/2014 11:47,SEA00101,620.141,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1982
12,443,10/13/2014 11:37,10/13/2014 11:47,SEA00461,634.087,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1984
13,444,10/13/2014 11:37,10/13/2014 11:47,SEA00044,614.336,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1955
14,445,10/13/2014 11:37,10/13/2014 11:47,SEA00298,601.463,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1953
15,446,10/13/2014 11:37,10/13/2014 11:47,SEA00106,618.781,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Female,1958
16,447,10/13/2014 11:37,10/13/2014 11:47,SEA00108,617.085,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1959
17,448,10/13/2014 11:37,10/13/2014 11:47,SEA00236,600.05,Occidental Park / Occidental Ave S & S Washing...,King Street Station Plaza / 2nd Ave Extension ...,PS-04,PS-05,Member,Male,1950
18,450,10/13/2014 11:40,10/13/2014 11:49,SEA00107,499.734,Occidental Park / Occidental Ave S & S Washing...,City Hall / 4th Ave & James St,PS-04,CBD-07,Member,Female,1976
19,452,10/13/2014 11:41,10/13/2014 11:51,SEA00259,575.307,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Male,1986
20,453,10/13/2014 11:41,10/13/2014 11:51,SEA00178,571.807,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Male,1953
21,454,10/13/2014 11:41,10/13/2014 11:51,SEA00123,563.763,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Male,1986
22,455,10/13/2014 11:42,10/13/2014 11:49,SEA00373,437.689,Occidental Park / Occidental Ave S & S Washing...,City Hall / 4th Ave & James St,PS-04,CBD-07,Member,Male,1967
23,456,10/13/2014 11:43,10/13/2014 11:51,SEA00121,483.154,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Female,1986
24,457,10/13/2014 11:43,10/13/2014 11:51,SEA00029,479.382,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Female,1987
25,458,10/13/2014 11:43,10/13/2014 11:52,SEA00436,533.532,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Female,1987
26,459,10/13/2014 11:43,10/13/2014 11:51,SEA00118,481.629,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Male,1974
27,460,10/13/2014 11:43,10/13/2014 11:51,SEA00177,460.772,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Male,1967
28,461,10/13/2014 11:43,10/13/2014 11:51,SEA00348,459.165,Occidental Park / Occidental Ave S & S Washing...,1st Ave & Marion St,PS-04,CBD-05,Member,Female,1983
29,462,10/13/2014 11:44,10/13/2014 11:55,SEA00459,680.457,Occidental Park / Occidental Ave S & S Washing...,2nd Ave & Spring St,PS-04,CBD-06,Member,Male,1970
...,...,...,...,...,...,...,...,...,...,...,...,...
286829,255216,8/31/2016 20:13,8/31/2016 20:34,SEA00309,1233.725,3rd Ave & Broad St,Pier 66 / Alaskan Way & Bell St,BT-01,WF-03,Short-Term Pass Holder,NaN,NaN
286830,255217,8/31/2016 20:32,8/31/2016 20:56,SEA00034,1472.611,6th Ave S & S King St,Cal Anderson Park / 11th Ave & Pine St,ID-04,CH-08,Short-Term Pass Holder,NaN,NaN
286831,255218,8/31/2016 20:32,8/31/2016 20:56,SEA00023,1462.959,6th Ave S & S King St,Cal Anderson Park / 11th Ave & Pine St,ID-04,CH-08,Short-Term Pass Holder,NaN,NaN
286832,255219,8/31/2016 20:32,8/31/2016 20:54,SEA00499,1275.8,2nd Ave & Spring St,Harvard Ave & E Pine St,CBD-06,CH-09,Short-Term Pass Holder,NaN,NaN
286833,255220,8/31/2016 20:33,8/31/2016 20:56,SEA00490,1403.165,6th Ave S & S King St,Cal Anderson Park / 11th Ave & Pine St,ID-04,CH-08,Short-Term Pass Holder,NaN,NaN
286834,255221,8/31/2016 20:33,8/31/2016 20:57,SEA00442,1411.592,6th Ave S & S King St,Cal Anderson Park / 11th Ave & Pine St,ID-04,CH-08,Short-Term Pass Holder,NaN,NaN
286835,255222,8/31/2016 20:33,8/31/2016 20:36,SEA00297,193.605,Summit Ave E & E Republican St,REI / Yale Ave N & John St,CH-03,SLU-01,Member,Male,1978
286836,255223,8/31/2016 20:43,8/31/2016 20:47,SEA00321,270.934,15th Ave E & E Thomas St,Bellevue Ave & E Pine St,CH-05,CH-12,Member,Male,1988
286837,255224,8/31/2016 20:44,8/31/2016 20:48,SEA00116,214.717,Union St & 4th Ave,Westlake Ave & 6th Ave,CBD-04,SLU-15,Member,Male,1985
286838,255225,8/31/2016 20:57,8/31/2016 21:00,SEA00247,187.685,12th Ave & E Mercer St,Cal Anderson Park / 11th Ave & Pine St,CH-15,CH-08,Member,Male,1995
286839,255226,8/31/2016 20:58,8/31/2016 21:02,SEA00164,271.667,Seattle University / E Columbia St & 12th Ave,Cal Anderson Park / 11th Ave & Pine St,FH-04,CH-08,Short-Term Pass Holder,NaN,NaN
286840,255227,8/31/2016 20:58,8/31/2016 21:02,SEA00107,273.808,Seattle University / E Columbia St & 12th Ave,Cal Anderson Park / 11th Ave & Pine St,FH-04,CH-08,Short-Term Pass Holder,NaN,NaN
286841,255228,8/31/2016 21:11,8/31/2016 21:15,SEA00499,235.553,Harvard Ave & E Pine St,E Harrison St & Broadway Ave E,CH-09,CH-02,Member,Male,1987
286842,255229,8/31/2016 21:16,8/31/2016 21:32,SEA00045,970.096,Summit Ave & E Denny Way,Thomas St & 5th Ave N,CH-01,SLU-22,Member,Male,1994
286843,255230,8/31/2016 21:27,8/31/2016 21:30,SEA00056,198.324,Republican St & Westlake Ave N,Dexter Ave N & Aloha St,SLU-04,SLU-02,Member,Male,1981
286844,255231,8/31/2016 21:35,8/31/2016 21:46,SEA00288,671.917,NE Pacific St/UW Medical Center,Burke-Gilman Trail / NE Blakeley St & 24th Ave NE,UW-11,UD-01,Member,Female,1976
286845,255232,8/31/2016 21:59,8/31/2016 22:04,SEA00499,308.484,E Harrison St & Broadway Ave E,Bellevue Ave & E Pine St,CH-02,CH-12,Member,Male,1989
286846,255233,8/31/2016 22:02,8/31/2016 22:17,SEA00074,905.417,Key Arena / 1st Ave N & Harrison St,Pier 66 / Alaskan Way & Bell St,SLU-19,WF-03,Member,Female,1974
286847,255234,8/31/2016 22:02,8/31/2016 22:17,SEA00448,879.16,Key Arena / 1st Ave N & Harrison St,Pier 66 / Alaskan Way & Bell St,SLU-19,WF-03,Member,Male,1981
286848,255235,8/31/2016 22:10,8/31/2016 22:28,SEA00144,1084.191,Seattle Aquarium / Alaskan Way S & Elliott Bay...,Key Arena / 1st Ave N & Harrison St,WF-04,SLU-19,Short-Term Pass Holder,NaN,NaN
286849,255236,8/31/2016 22:13,8/31/2016 22:25,SEA00254,674.993,3rd Ave & Broad St,Occidental Park / Occidental Ave S & S Washing...,BT-01,PS-04,Member,Male,1984
286850,255237,8/31/2016 22:37,8/31/2016 22:39,SEA00330,144.477,Summit Ave & E Denny Way,Summit Ave E & E Republican St,CH-01,CH-03,Member,Male,1990
286851,255238,8/31/2016 22:44,8/31/2016 23:03,SEA00336,1106.063,Pier 69 / Alaskan Way & Clay St,2nd Ave & Blanchard St,WF-01,BT-05,Short-Term Pass Holder,NaN,NaN
286852,255239,8/31/2016 22:44,8/31/2016 23:03,SEA00394,1116.502,Pier 69 / Alaskan Way & Clay St,2nd Ave & Blanchard St,WF-01,BT-05,Short-Term Pass Holder,NaN,NaN
286853,255240,8/31/2016 22:47,8/31/2016 23:03,SEA00370,920.672,Pier 69 / Alaskan Way & Clay St,2nd Ave & Blanchard St,WF-01,BT-05,Short-Term Pass Holder,NaN,NaN
286854,255241,8/31/2016 23:34,8/31/2016 23:45,SEA00201,679.532,Harvard Ave & E Pine St,2nd Ave & Spring St,CH-09,CBD-06,Short-Term Pass Holder,NaN,NaN
286855,255242,8/31/2016 23:48,9/1/2016 0:20,SEA00247,1965.418,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN
286856,255243,8/31/2016 23:47,9/1/2016 0:20,SEA00300,1951.173,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN
286857,255244,8/31/2016 23:49,9/1/2016 0:20,SEA00047,1883.299,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN
286858,255245,8/31/2016 23:49,9/1/2016 0:20,SEA00442,1896.031,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN

In [5]:
#to do calculations, first,I'll change the datatype from objects to numeric
df.dtypes

trip_id              object
starttime            object
stoptime             object
bikeid               object
tripduration         object
from_station_name    object
to_station_name      object
from_station_id      object
to_station_id        object
usertype             object
gender               object
birthyear            object
dtype: object

In [6]:
# data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
df['trip_id'] = pd.to_numeric(df['trip_id'],downcast='integer')
df['birthyear'] = pd.to_numeric(df['birthyear'],downcast='integer')
df['tripduration'] = pd.to_numeric(df['tripduration'],downcast='float')
df['tripduration'] = pd.to_numeric(df['tripduration'],downcast='float')

df.dtypes

trip_id                int32
starttime             object
stoptime              object
bikeid                object
tripduration         float32
from_station_name     object
to_station_name       object
from_station_id       object
to_station_id         object
usertype              object
gender                object
birthyear            float64
dtype: object

#### Now, the data is ready

In [7]:
#What is the average trip duration for a borrowed bicycle?
df['tripduration'].mean()

1178.3542

In [8]:
#What’s the most common age of a bicycle-sharer?
pd.datetime.now().year - df['birthyear'].value_counts().index[0]

34.0

In [9]:
#What’s the average number of bikes at a given bike station?
# *** later ***

In [10]:
#When a bike station is modified, is it more likely that it’ll lose bikes or gain bikes? How do you know?
# *** later ***

## Part2: Weather data

In [11]:
#Given all the weather data here

In [12]:
df2 = pd.read_csv('./archive/weather.csv')
df2

,Date,Max_Temperature_F,Mean_Temperature_F,Min_TemperatureF,Max_Dew_Point_F,MeanDew_Point_F,Min_Dewpoint_F,Max_Humidity,Mean_Humidity,Min_Humidity,...,Mean_Sea_Level_Pressure_In,Min_Sea_Level_Pressure_In,Max_Visibility_Miles,Mean_Visibility_Miles,Min_Visibility_Miles,Max_Wind_Speed_MPH,Mean_Wind_Speed_MPH,Max_Gust_Speed_MPH,Precipitation_In,Events
0,10/13/2014,71,62.0,54,55,51,46,87,68,46,...,29.79,29.65,10,10,4,13,4,21,0.00,Rain
1,10/14/2014,63,59.0,55,52,51,50,88,78,63,...,29.75,29.54,10,9,3,10,5,17,0.11,Rain
2,10/15/2014,62,58.0,54,53,50,46,87,77,67,...,29.71,29.51,10,9,3,18,7,25,0.45,Rain
3,10/16/2014,71,61.0,52,49,46,42,83,61,36,...,29.95,29.81,10,10,10,9,4,-,0.00,Rain
4,10/17/2014,64,60.0,57,55,51,41,87,72,46,...,29.78,29.73,10,10,6,8,3,-,0.14,Rain
5,10/18/2014,68,64.0,59,59,57,55,90,83,68,...,29.90,29.80,10,8,2,10,4,-,0.31,Rain
6,10/19/2014,73,64.0,55,57,55,53,94,74,52,...,29.73,29.67,10,10,6,10,3,18,0.00,NaN
7,10/20/2014,66,60.0,55,57,54,50,90,78,67,...,29.74,29.69,10,10,5,12,5,-,0.44,Rain
8,10/21/2014,64,58.0,55,52,49,46,87,70,58,...,29.85,29.74,10,10,6,15,8,21,0.10,Rain
9,10/22/2014,60,58.0,57,55,53,48,88,81,67,...,29.68,29.56,10,6,2,14,8,22,1.43,Rain
10,10/23/2014,62,55.0,50,49,47,44,86,76,62,...,29.83,29.71,10,10,10,15,9,22,0.35,Rain
11,10/24/2014,60,56.0,51,50,47,44,86,75,60,...,29.96,29.74,10,10,8,8,4,-,0.13,Rain
12,10/25/2014,64,58.0,52,53,49,44,87,78,58,...,29.48,29.26,10,10,6,24,6,41,0.37,Rain
13,10/26/2014,59,52.0,48,48,44,42,86,71,62,...,29.98,29.76,10,10,10,20,12,30,0.05,Rain
14,10/27/2014,62,54.0,45,46,43,41,87,72,48,...,30.09,29.98,10,10,10,7,4,-,0.01,Rain
15,10/28/2014,62,56.0,51,54,50,45,88,80,72,...,29.88,29.84,10,8,2,14,5,-,0.34,Rain
16,10/29/2014,64,59.0,54,54,51,50,88,76,60,...,30.06,29.94,10,10,9,15,7,24,0.04,Rain
17,10/30/2014,62,58.0,55,55,53,50,88,82,75,...,29.83,29.74,10,9,2,8,2,-,0.67,Rain
18,10/31/2014,59,54.0,52,52,49,46,89,83,67,...,29.79,29.69,10,8,2,8,4,-,0.77,Rain
19,11/1/2014,55,52.0,48,48,45,42,89,78,62,...,29.92,29.84,10,10,7,6,1,-,0.00,NaN
20,11/2/2014,57,51.0,45,52,47,42,90,82,62,...,30.10,30.06,10,9,4,9,5,-,0.11,Rain
21,11/3/2014,60,58.0,55,53,51,48,84,80,75,...,30.08,30.01,10,9,3,13,8,20,0.24,Rain
22,11/4/2014,61,58.0,55,54,51,48,90,79,67,...,30.14,29.99,10,9,3,10,6,-,0.05,Rain
23,11/5/2014,61,57.0,53,55,51,48,90,79,64,...,30.15,29.96,10,10,3,7,2,-,0.27,Rain
24,11/6/2014,64,60.0,54,55,50,45,90,75,58,...,29.99,29.80,10,10,4,20,8,37,0.22,Rain
25,11/7/2014,59,52.0,45,45,43,40,86,72,53,...,30.41,30.31,10,10,10,7,3,-,0.00,NaN
26,11/8/2014,55,48.0,42,44,42,39,93,78,60,...,30.25,30.06,10,8,2,7,1,-,0.00,NaN
27,11/9/2014,57,52.0,48,50,46,43,87,80,72,...,29.93,29.82,10,9,3,12,6,16,0.29,Rain
28,11/10/2014,54,48.0,43,43,40,34,86,71,54,...,30.17,30.07,10,10,10,8,2,-,0.00,NaN
29,11/11/2014,48,42.0,36,39,18,3,80,42,20,...,30.28,30.18,10,10,10,15,5,22,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,8/2/2016,73,64.0,57,53,51,50,78,66,49,...,30.13,30.07,10,10,10,12,6,17,0.00,NaN
660,8/3/2016,75,66.0,60,53,52,51,72,62,45,...,30.24,30.16,10,10,10,10,6,NaN,0.00,NaN
661,8/4/2016,80,69.0,59,56,53,51,81,58,38,...,30.04,29.91,10,10,10,13,5,21,0.00,NaN
662,8/5/2016,79,70.0,61,54,51,46,75,56,32,...,29.92,29.89,10,10,10,9,4,NaN,0.00,NaN
663,8/6/2016,72,63.0,55,51,49,48,77,62,45,...,29.97,29.91,10,10,10,10,6,NaN,0.00,NaN
664,8/7/2016,72,66.0,60,56,52,49,83,69,49,...,29.92,29.89,10,10,10,9,4,NaN,0.03,Rain
665,8/8/2016,73,64.0,57,54,53,48,84,69,44,...,29.97,29.95,10,10,10,9,4,NaN,0.00,NaN
666,8/9/2016,72,66.0,60,55,54,53,83,70,53,...,30.01,29.98,10,10,10,10,3,NaN,0.00,NaN
667,8/10/2016,75,68.0,60,56,55,54,83,67,48,...,30.07,30.04,10,10,10,12,2,17,0.00,NaN
668,8/11/2016,80,70.0,61,57,56,54,81,63,47,...,30.10,30.06,10,10,10,12,4,20,0.00,NaN
669,8/12/2016,87,75.0,63,59,57,55,78,56,36,...,30.05,29.98,10,10,10,10,3,NaN,0.00,NaN
670,8/13/2016,90,78.0,66,60,56,51,78,52,28,...,29.98,29.93,10,10,10,8,2,NaN,0.00,NaN
671,8/14/2016,82,71.0,60,54,52,44,78,51,25,...,30.01,29.96,10,10,10,10,4,NaN,0.00,NaN
672,8/15/2016,84,72.0,61,57,55,53,78,57,37,...,30.06,30.02,10,10,10,9,2,NaN,0.00,NaN
673,8/16/2016,81,69.0,57,56,54,51,90,62,35,...,30.09,30.04,10,10,10,8,2,NaN,0.00,NaN
674,8/17/2016,79,70.0,60,54,53,50,80,56,40,...,30.06,30.00,10,10,10,12,4,NaN,0.00,NaN
675,8/18/2016,86,73.0,60,63,59,49,72,57,45,...,30.00,29.93,10,10,10,16,8,NaN,0.00,NaN
676,8/19/2016,95,60.0,26,77,54,9,88,48,23,...,29.96,29.88,10,10,10,16,8,NaN,0.00,NaN
677,8/20/2016,91,78.0,64,57,53,48,70,44,26,...,29.87,29.78,10,10,10,10,3,NaN,0.00,NaN
678,8/21/2016,73,66.0,60,55,54,52,83,68,48,...,29.89,29.81,10,10,10,14,8,NaN,0.00,NaN
679,8/22/2016,72,64.0,57,59,51,46,93,64,40,...,30.07,29.99,10,10,10,14,8,NaN,0.00,NaN
680,8/23/2016,79,67.0,55,55,51,48,83,58,39,...,30.16,30.12,10,10,10,17,7,NaN,0.00,NaN
681,8/24/2016,82,70.0,57,57,55,54,89,60,39,...,30.18,30.12,10,10,10,20,5,NaN,0.00,NaN
682,8/25/2016,93,77.0,61,59,54,50,81,51,22,...,30.05,29.94,10,10,10,14,4,NaN,0.00,NaN
683,8/26/2016,88,74.0,60,57,52,45,82,45,22,...,29.89,29.79,10,10,10,10,4,NaN,0.00,NaN
684,8/27/2016,72,66.0,61,57,54,50,81,65,46,...,29.88,29.77,10,10,10,16,9,NaN,0.00,NaN
685,8/28/2016,75,68.0,59,54,52,50,80,65,44,...,30.06,30.01,10,10,10,12,9,NaN,0.00,NaN
686,8/29/2016,81,68.0,55,55,53,50,89,65,39,...,30.02,29.95,10,10,6,9,4,NaN,0.00,NaN
687,8/30/2016,70,64.0,57,55,53,52,83,69,53,...,30.01,29.97,10,10,10,14,9,18,0.00,NaN
688,8/31/2016,71,65.0,59,61,56,52,90,77,63,...,29.97,29.96,10,10,8,14,8,NaN,0.00,Rain

In [13]:
# lucky me, pretty clean data
df2.dtypes

Date                           object
Max_Temperature_F               int64
Mean_Temperature_F            float64
Min_TemperatureF                int64
Max_Dew_Point_F                 int64
MeanDew_Point_F                 int64
Min_Dewpoint_F                  int64
Max_Humidity                    int64
Mean_Humidity                   int64
Min_Humidity                    int64
Max_Sea_Level_Pressure_In     float64
Mean_Sea_Level_Pressure_In    float64
Min_Sea_Level_Pressure_In     float64
Max_Visibility_Miles            int64
Mean_Visibility_Miles           int64
Min_Visibility_Miles            int64
Max_Wind_Speed_MPH              int64
Mean_Wind_Speed_MPH             int64
Max_Gust_Speed_MPH             object
Precipitation_In              float64
Events                         object
dtype: object

In [14]:
# find the average precipitation per month, and the median precipitation.
df2['Precipitation_In'].median()
# *** later ***

0.0

In [15]:
#Come up with 3 more questions that can be answered with this data set.
# *** later ***